### ISSUE TITLE
conig configReader.py

### ISSUE THREAD

**Issue by ghost** [SeanWoo/SpotifyTgBot#1]
Hello good afternoon, sorry. I could explain to me to ask for each configuration

 BASE_DOMEN = obj["BASE_DOMEN"]  Here specifically what data is placed?
REDIRECT_URL = obj["REDIRECT_URL"]  nose that would be redirect url
DATABASE_CONNECT = obj["DATABASE_CONNECT"]    Here specifically what data is placed?
SPOTIFY_SCOPE = obj["SPOTIFY_SCOPE"] 

I am sorry,  and from now thank you very much

**Comment by SeanWoo** [comment]
Hello!

**BASE_DOMEN** is deprecated.

**REDIRECT_URL** is an array with the full path to your callback in the format https: // <domen> / callback / {id}
where id is any set of characters.

**DATABASE_CONNECT** is an object with **SERVER**, **USER**, **PASSWORD**, **DATABASE** fields.
**SERVER** is the domain of your base
**USER** and **PASSWORD** - username and password
**DATABASE** is the name of your database.

**SPOTIFY_SCOPE** is the permissions the user gives you. See: https://developer.spotify.com/documentation/general/guides/scopes/

> Hello good afternoon, sorry. I could explain to me to ask for each configuration
> 
> BASE_DOMEN = obj["BASE_DOMEN"] Here specifically what data is placed?
> REDIRECT_URL = obj["REDIRECT_URL"] nose that would be redirect url
> DATABASE_CONNECT = obj["DATABASE_CONNECT"] Here specifically what data is placed?
> SPOTIFY_SCOPE = obj["SPOTIFY_SCOPE"]
> 
> I am sorry, and from now thank you very much

**Comment by ghost** [comment]
Can I contact you by telegram or some other means?

**Comment by SeanWoo** [comment]
> Can I contact you by telegram or some other means?

Telegram: @SeanWoo
